//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hermes2018.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hermes2018.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor introduzca una dirección de correo válida..
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dato {0} debe tener como máximo {1} elementos..
        /// </summary>
        public static string maximoentero {
            get {
                return ResourceManager.GetString("maximoentero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El listado de {0} está incompleto..
        /// </summary>
        public static string maximolistado {
            get {
                return ResourceManager.GetString("maximolistado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dato {0} debe tener al menos {1} elementos..
        /// </summary>
        public static string minimoentero {
            get {
                return ResourceManager.GetString("minimoentero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El listado de {0} está incompleto..
        /// </summary>
        public static string minimolistado {
            get {
                return ResourceManager.GetString("minimolistado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dato es requerido..
        /// </summary>
        public static string requerido {
            get {
                return ResourceManager.GetString("requerido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dato {0} es requerido..
        /// </summary>
        public static string required {
            get {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El dato {0} no debe sobrepasar los {1} caracteres..
        /// </summary>
        public static string stringlength {
            get {
                return ResourceManager.GetString("stringlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifique el nombre del titular..
        /// </summary>
        public static string titular {
            get {
                return ResourceManager.GetString("titular", resourceCulture);
            }
        }
    }
}
